### ISSUE TITLE
Categories Icons looking weird.

### ISSUE THREAD

**Issue by FulI-Name** [nethruster/ptemplate#37]

**Comment by BadFCA** [comment]
![image](https://user-images.githubusercontent.com/42716008/89123250-a6844e80-d4d6-11ea-9a89-1464e4500322.png)
Here's the image. Hopefully someone can find the reason....

**Comment by gariasf** [comment]
Hello @FulI-Name 

Can you tell us in which browser (and version) is this issue happening?

**Comment by FulI-Name** [comment]
Chrome and Idk how to check version. Should be latest @gariasf

**Comment by FulI-Name** [comment]
Chrome 84 on Windows 10

**Comment by FulI-Name** [comment]
Other browsers seem to work fine actually

**Comment by FulI-Name** [comment]
So Ideas?
