### ISSUE TITLE
outdate dependency

### ISSUE THREAD

**Issue by AronWaterAron** [nethruster/ptemplate#46]
![image](https://user-images.githubusercontent.com/36737465/119234297-b5b8b380-bb5f-11eb-8e71-604509ad75f4.png)

any updates?  THX

**Comment by claudio4** [comment]
Updating dependencies is kinda hard as backwards compatibly for certain tools (especially WebPack) have been broken. And having outdated dependencies in a front-end only project it's not that concerning. So probably this is a won't fix.

That being said, we might build a brand-new version from the ground. But there is no ETA nor a confirmation that it will ever reach development.
