### ISSUE TITLE
Pestaña Work

### ISSUE THREAD

**Issue by Drascor** [nethruster/ptemplate#5]
En la pestaña My Work si en un proyecto no has puesto sitio web ni código fuente, se que da un "espacio" vacío como si estuviese reservado, en vez de extenderse la descripción para ocupar todo el ancho.

Un saludo y gran trabajo.

**Comment by gariasf** [comment]
Hola Drascor, esto ha sido arreglado en 38a17882b6916e515dd7ae4e63a978913e038784, gracias por tu participación.
