### ISSUE TITLE
Only first two icons have hover effect rest two does not have it

### ISSUE THREAD

**Issue by shreyshreyansh** [nethruster/ptemplate#52]
![Screenshot 2021-09-28 171813](https://user-images.githubusercontent.com/53744971/135081028-8511a483-0e45-4bd5-a187-2ccf8fbbce1d.jpg)

**Comment by claudio4** [comment]
Are you sure they are not working? Be aware that both the Github and the mail icon have a black hover color,, so the effect is very subtle, please try to change their `hoverColor` in the config.js to something like red (`#ff0000`) to check whether it isn't working or it is just too subtle.

**Comment by Miguel-Dorta** [comment]
Closing the issue for inactivity. It's presumed "not a bug".
