### ISSUE TITLE
Not exactly an Issue, though I need some help

### ISSUE THREAD

**Issue by BetaDv** [nethruster/ptemplate#54]
How could I set this Website UP to work only with NPM? I am looking to edit it accordingly to make a Discord Bot Website, possible dashboard aswell. But I need a clean website startup, and this looks perfect for my bot.

I also only want the HTML / CSS and JS (to animate) side of things, not full webpage with backend code

**Comment by Miguel-Dorta** [comment]
Hi!

Sorry for the delayed response.

You have the commands to build the website with NPM in the [README.md](https://github.com/nethruster/ptemplate/blob/master/README.md) file. You'll need an HTTP server to serve the files. I like NGINX, but that's up to you.

When you build the page you'll get the HTML, CSS and JS. This project has no back-end code.
